In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
df = pd.read_parquet('../data/raw/sih_PR_2023_01.parquet')
print (f"Dados carregados: {len(df)} linhas")

Dados carregados: 1022423 linhas

In [3]:
df.describe

<bound method NDFrame.describe of         SP_GESTOR SP_UF SP_AA SP_MM  SP_CNES        SP_NAIH  SP_PROCREA  \
0          410000    41  2023    01  2729385  4123106805576  0301060088
1          410000    41  2023    01  2729385  4123106805576  0301060088
2          410000    41  2023    01  2729385  4123106805598  0303070129
3          410000    41  2023    01  2729385  4123106805598  0303070129
4          410000    41  2023    01  2729385  4123106805598  0303070129
...           ...   ...   ...   ...      ...            ...         ...
1022418    410000    41  2023    01  2742039  4123106972919  0301060088
1022419    410000    41  2023    01  2742039  4123106972920  0301060088
1022420    410000    41  2023    01  2742039  4123106972941  0301060088
1022421    410000    41  2023    01  2742039  4123106972952  0301060088
1022422    410000    41  2023    01  2742039  4123106972963  0301060088

        SP_DTINTER SP_DTSAIDA SP_NUM_PR  ...        SP_PF_DOC       SP_PJ_DOC  \
0         20230126   20230127            ...  000000000000000  00000002729687
1         20230126   20230127            ...  000000000000000  00000002729687
2         20230128   20230130            ...  702007890355581  00000000000000
3         20230128   20230130            ...  000000000000000  00000002729385
4         20230128   20230130            ...  707802687727711  00000002781859
...            ...        ...       ...  ...              ...             ...
1022418   20230113   20230114            ...  000000000000000  00000002742039
1022419   20230105   20230105            ...  000000000000000  00000002742039
1022420   20230110   20230110            ...  000000000000000  00000002742039
1022421   20230103   20230104            ...  000000000000000  00000002742039
1022422   20230105   20230106            ...  000000000000000  00000002742039

        IN_TP_VAL SEQUENCIA                REMESSA SERV_CLA SP_CIDPRI  \
0               1     33367  HE41000001N202301.DTS   000000       I64
1               1     33367  HE41000001N202301.DTS   000000       I64
2               2     33368  HE41000001N202301.DTS   000000      K838
3               1     33368  HE41000001N202301.DTS   000000      K838
4               1     33368  HE41000001N202301.DTS   128004      K838
...           ...       ...                    ...      ...       ...
1022418         1     15423  HE41000001N202301.DTS   000000      T012
1022419         1     15424  HE41000001N202301.DTS   000000       I64
1022420         1     15425  HE41000001N202301.DTS   000000      T012
1022421         1     15426  HE41000001N202301.DTS   000000      T012
1022422         1     15427  HE41000001N202301.DTS   000000      T012

        SP_CIDSEC SP_QT_PROC SP_U_AIH
0            0000          1        0
1            0000          1        0
2            0000          0        1
3            0000          2        0
4            0000          2        0
...           ...        ...      ...
1022418      0000          1        0
1022419      0000          1        0
1022420      0000          1        0
1022421      0000          1        0
1022422      0000          1        0

[1022423 rows x 36 columns]>

In [4]:
print(f"Quantidade de colunas:{df.shape[1]}")
print(f"Registros: {len(df):,}")
print(f"Colunas:{df.columns.tolist()}")
print(f"Tipos: {df.dtypes}")

Quantidade de colunas:36
Registros: 1,022,423
Colunas:['SP_GESTOR', 'SP_UF', 'SP_AA', 'SP_MM', 'SP_CNES', 'SP_NAIH', 'SP_PROCREA', 'SP_DTINTER', 'SP_DTSAIDA', 'SP_NUM_PR', 'SP_TIPO', 'SP_CPFCGC', 'SP_ATOPROF', 'SP_TP_ATO', 'SP_QTD_ATO', 'SP_PTSP', 'SP_NF', 'SP_VALATO', 'SP_M_HOSP', 'SP_M_PAC', 'SP_DES_HOS', 'SP_DES_PAC', 'SP_COMPLEX', 'SP_FINANC', 'SP_CO_FAEC', 'SP_PF_CBO', 'SP_PF_DOC', 'SP_PJ_DOC', 'IN_TP_VAL', 'SEQUENCIA', 'REMESSA', 'SERV_CLA', 'SP_CIDPRI', 'SP_CIDSEC', 'SP_QT_PROC', 'SP_U_AIH']
Tipos: SP_GESTOR     object
SP_UF         object
SP_AA         object
SP_MM         object
SP_CNES       object
SP_NAIH       object
SP_PROCREA    object
SP_DTINTER    object
SP_DTSAIDA    object
SP_NUM_PR     object
SP_TIPO       object
SP_CPFCGC     object
SP_ATOPROF    object
SP_TP_ATO     object
SP_QTD_ATO    object
SP_PTSP       object
SP_NF         object
SP_VALATO     object
SP_M_HOSP     object
SP_M_PAC      object
SP_DES_HOS    object
SP_DES_PAC    object
SP_COMPLEX    object
SP_FINANC     object
SP_CO_FAEC    object
SP_PF_CBO     object
SP_PF_DOC     object
SP_PJ_DOC     object
IN_TP_VAL     object
SEQUENCIA     object
REMESSA       object
SERV_CLA      object
SP_CIDPRI     object
SP_CIDSEC     object
SP_QT_PROC    object
SP_U_AIH      object
dtype: object

NAO USAREMOS TODAS AS 36 COLUNAS, SÃO MUITAS. PRECISA DE UM TRATAMENTO DE TIPO POIS TODAS ESTÃO COMO OBJECT, ATRAPALHANDO NOSSAS FUTURAS MÉTRICAS.

In [5]:
nulos = df.isnull().sum()
nulos_percent = (nulos / len(df))*100

df_nulos = pd.DataFrame({
    'Nulos' : nulos,
    'Percentual' : nulos_percent

}).sort_values('Nulos', ascending=False)
print(f"Valores Nulos por coluna:")
df_nulos

Valores Nulos por coluna:

            Nulos  Percentual
SP_GESTOR       0         0.0
SP_UF           0         0.0
SP_DES_HOS      0         0.0
SP_DES_PAC      0         0.0
SP_COMPLEX      0         0.0
SP_FINANC       0         0.0
SP_CO_FAEC      0         0.0
SP_PF_CBO       0         0.0
SP_PF_DOC       0         0.0
SP_PJ_DOC       0         0.0
IN_TP_VAL       0         0.0
SEQUENCIA       0         0.0
REMESSA         0         0.0
SERV_CLA        0         0.0
SP_CIDPRI       0         0.0
SP_CIDSEC       0         0.0
SP_QT_PROC      0         0.0
SP_M_PAC        0         0.0
SP_M_HOSP       0         0.0
SP_VALATO       0         0.0
SP_DTSAIDA      0         0.0
SP_AA           0         0.0
SP_MM           0         0.0
SP_CNES         0         0.0
SP_NAIH         0         0.0
SP_PROCREA      0         0.0
SP_DTINTER      0         0.0
SP_NUM_PR       0         0.0
SP_NF           0         0.0
SP_TIPO         0         0.0
SP_CPFCGC       0         0.0
SP_ATOPROF      0         0.0
SP_TP_ATO       0         0.0
SP_QTD_ATO      0         0.0
SP_PTSP         0         0.0
SP_U_AIH        0         0.0

NAO TEMOS COLUNAS COM VALORES NULOS

In [6]:
colunas_essenciais = [
       'SP_GESTOR',   # Código do Município
    'SP_CNES',     # ID do Hospital
    'SP_CIDPRI',   # Código CID-10 da doença
    'SP_DTINTER',  # Data de Internação
    'SP_DTSAIDA',  # Data de Saída
    'SP_VALATO',   # Valor do Ato Profissional
    'SP_M_PAC',    # Município do Paciente
    'SP_AA',       # Ano
    'SP_MM'        # Mês
]

df_filtrado = df[colunas_essenciais].copy()
df_filtrado

,SP_GESTOR,SP_CNES,SP_CIDPRI,SP_DTINTER,SP_DTSAIDA,SP_VALATO,SP_M_PAC,SP_AA,SP_MM
0,410000,2729385,I64,20230126,20230127,0.00,411270,2023,01
1,410000,2729385,I64,20230126,20230127,0.00,411270,2023,01
2,410000,2729385,K838,20230128,20230130,41.95,410980,2023,01
3,410000,2729385,K838,20230128,20230130,16.00,410980,2023,01
4,410000,2729385,K838,20230128,20230130,16.78,410980,2023,01
...,...,...,...,...,...,...,...,...,...
1022418,410000,2742039,T012,20230113,20230114,33.34,411930,2023,01
1022419,410000,2742039,I64,20230105,20230105,33.34,411930,2023,01
1022420,410000,2742039,T012,20230110,20230110,33.34,411930,2023,01
1022421,410000,2742039,T012,20230103,20230104,33.34,411930,2023,01
1022422,410000,2742039,T012,20230105,20230106,33.34,353480,2023,01

In [8]:
df_filtrado['SP_DTINTER'] = pd.to_datetime(df_filtrado['SP_DTINTER'], format='%Y%m%d', errors='coerce')
df_filtrado['SP_DTSAIDA'] = pd.to_datetime(df_filtrado['SP_DTSAIDA'], format='%Y%m%d', errors ='coerce')

df_filtrado['SP_GESTOR'] = pd.to_numeric(df_filtrado['SP_GESTOR'], errors = 'coerce' )

df_filtrado['SP_AA'] = pd.to_numeric(df_filtrado['SP_AA'], errors='coerce').fillna(0).astype(int)
df_filtrado['SP_MM'] = pd.to_numeric(df_filtrado['SP_MM'], errors='coerce').fillna(0).astype(int)

df_filtrado.dtypes

SP_GESTOR              int64
SP_CNES               object
SP_CIDPRI             object
SP_DTINTER    datetime64[ns]
SP_DTSAIDA    datetime64[ns]
SP_VALATO             object
SP_M_PAC              object
SP_AA                  int64
SP_MM                  int64
dtype: object